# Generated by Django 6.0.6 on 2026-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
