# Generated by Django 6.0.6 on 2026-06-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=4.5)),
                ('stock', models.IntegerField(default=10)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
